"""Init

Revision ID: 1942ee4e5ce9
Revises: ccc3ca2bbb14
Create Date: 2023-10-09 19:37:18.261004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1942ee4e5ce9'
down_revision: Union[str, None] = 'ccc3ca2bbb14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message_history', 'chat_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('message_history_chat_id_fkey', 'message_history', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('message_history_chat_id_fkey', 'message_history', 'chat', ['chat_id'], ['id'], ondelete='CASCADE')
    op.alter_column('message_history', 'chat_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
