"""Init

Revision ID: 647fdd20168c
Revises: 73de0f49a6e6
Create Date: 2023-10-07 12:51:27.394373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '647fdd20168c'
down_revision: Union[str, None] = '73de0f49a6e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chat_user_id_key', 'chat', type_='unique')
    op.drop_constraint('message_history_chat_id_key', 'message_history', type_='unique')
    op.drop_constraint('message_history_user_id_key', 'message_history', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('message_history_user_id_key', 'message_history', ['user_id'])
    op.create_unique_constraint('message_history_chat_id_key', 'message_history', ['chat_id'])
    op.create_unique_constraint('chat_user_id_key', 'chat', ['user_id'])
    # ### end Alembic commands ###
