"""Init

Revision ID: 70624e91acc2
Revises: 647fdd20168c
Create Date: 2023-10-09 17:10:27.001047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70624e91acc2'
down_revision: Union[str, None] = '647fdd20168c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
    op.alter_column('users_profiles', 'file_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users_profiles', 'file_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_profiles', 'file_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users_profiles', 'file_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
    # ### end Alembic commands ###
