"""Init

Revision ID: 73de0f49a6e6
Revises: a55409224c58
Create Date: 2023-10-06 20:22:54.613541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73de0f49a6e6'
down_revision: Union[str, None] = 'a55409224c58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat', 'title_chat',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users_profiles', 'file_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users_profiles', 'file_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_profiles', 'file_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users_profiles', 'file_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('chat', 'title_chat',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
