"""Init

Revision ID: a55409224c58
Revises: 6902d6721c8e
Create Date: 2023-10-06 09:35:02.676263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a55409224c58'
down_revision: Union[str, None] = '6902d6721c8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat', sa.Column('title_chat', sa.String(), nullable=False))
    op.add_column('chat', sa.Column('file_url', sa.String(), nullable=True))
    op.add_column('chat', sa.Column('chat_data', sa.String(), nullable=True))
    op.add_column('users_profiles', sa.Column('file_url', sa.String(), nullable=False))
    op.add_column('users_profiles', sa.Column('file_name', sa.String(), nullable=False))
    op.drop_column('users_profiles', 'date_of_birth')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_profiles', sa.Column('date_of_birth', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('users_profiles', 'file_name')
    op.drop_column('users_profiles', 'file_url')
    op.drop_column('chat', 'chat_data')
    op.drop_column('chat', 'file_url')
    op.drop_column('chat', 'title_chat')
    # ### end Alembic commands ###
