# fly.toml app configuration file generated for llm-project-2023 on 2023-09-30T16:36:10+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "llm-project-2023"
primary_region = "ams"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
